version: '3'

networks:
  LARAVEL_INTERNAL_NETWORK:

services:

  mysql:
    image: arm64v8/mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sql_mode=''
    container_name: mysqldb
    restart: always
    ports:
      - 4306:3306
    volumes:
      - ~/docker/ind:/var/lib/mysqldb:rw
    environment:
      MYSQL_DATABASE: api-event-management
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAG: dev
      SERVICE_NAME: mysql
    networks:
      - LARAVEL_INTERNAL_NETWORK
volumes:
  mysql:
    driver: "local"
